**/.git
**/.idea
**/.fleet
**/.nova
**/.vscode
**/.zed

.env
.env.*
!.env.example
docker/.env.docker
docker/.env.docker.*
!docker/.env.docker.example

.phpunit.result.cache
auth.json
node_modules
vendor
scripts/.venv
pip-*

public/build
public/hot
public/storage

storage/*.key
storage/logs/*.log
storage/framework/cache/*
storage/framework/sessions/*
storage/framework/views/*
storage/pail

tests

**/*.log
**/Thumbs.db
**/.DS_Store
